### ISSUE TITLE
Cocoapods!!!!!

### ISSUE THREAD

**Issue by nicopuri** [nicopuri/SSNTextFieldManager#1]

**Comment by serg94** [comment]
you can find this https://github.com/serg94/SSNTextFieldDelegate
1. format ssn on paste
2. no need to input extra simbol for getting valid SSN, as this will not get you SSN if you will not press extra character on keyboard when inputting ssn data

and additional
1. it supports Cocoapods
2. written with Swift

**Comment by nicopuri** [comment]
@serg94 Great!
